# Generated by Django 4.1.1 on 2022-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_routine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='category',
            field=models.CharField(choices=[('숙제관련', 'HOMEWORK'), ('기상관련', 'MIRACLE')], max_length=128),
        ),
    ]
